-- =====================================================================
-- Tabla de ARTÍCULOS para el Dashboard de RehabiMovement
-- Ejecuta este script en: Supabase Dashboard -> SQL Editor -> New query
-- =====================================================================

create table if not exists public.articulos (
  id                bigint generated by default as identity primary key,
  titulo            text        not null,
  contenido         text,                              -- cuerpo del artículo (opcional)
  imagen_url        text,                              -- foto de portada en base64 (opcional)
  fecha_publicacion date        not null default current_date,
  mes               int         not null check (mes between 1 and 12),  -- 1 = Enero ... 12 = Diciembre
  anio              int         not null,
  status            int         not null default 1,    -- 1 = activo, 0 = inactivo
  created_at        timestamptz not null default now()
);

-- Índice para agrupar/filtrar rápido por mes y año
create index if not exists idx_articulos_anio_mes on public.articulos (anio, mes);

-- ---------------------------------------------------------------------
-- Row Level Security (RLS)
-- La app inicia sesión con su propia tabla "profiles" usando la llave
-- anónima (anon), por lo que las operaciones corren como rol "anon".
-- Estas políticas permiten leer y escribir, igual que el resto de la app.
-- ---------------------------------------------------------------------
alter table public.articulos enable row level security;

drop policy if exists "articulos_select" on public.articulos;
create policy "articulos_select"
  on public.articulos
  for select
  to anon, authenticated
  using (true);

drop policy if exists "articulos_modificar" on public.articulos;
create policy "articulos_modificar"
  on public.articulos
  for all
  to anon, authenticated
  using (true)
  with check (true);

-- =====================================================================
-- (Opcional) Datos de ejemplo para probar la vista por mes.
-- Puedes borrar este bloque si no lo necesitas.
-- =====================================================================
-- insert into public.articulos (titulo, contenido, mes, anio, fecha_publicacion) values
--   ('Bienvenidos a nuestro blog', 'Aquí compartiremos consejos de fisioterapia, rutinas y novedades de la clínica.', 1, 2026, '2026-01-10'),
--   ('5 ejercicios para la espalda', 'Una rutina sencilla para aliviar tensiones lumbares en casa.', 2, 2026, '2026-02-05');
